{% set name = "py3-validate-email" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3-validate-email-{{ version }}.tar.gz
  sha256: f927d69640fb27540acf543046e59a520ec7be21e4a10f15c959dc40ec5bbf2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dnspython ~=2.2
    - filelock ~=3.7
    - idna ~=3.3
    - python >=3.6
    - typing-extensions ~=4.4

test:
  imports:
    - validate_email
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://gitea.ksol.io/karolyi/py3-validate-email
  summary: Email validator with regex, blacklisted domains and SMTP checking.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
